GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmlsbCIsImlhdCI6MTYzMDU5ODI5NSwiZXhwIjoxNjMwNTk4MzMwfQ.EIqXud1sC42P85Hut6Ti9fkCInHZFFJ79NuaWa6DIAc
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmlsbCIsImlhdCI6MTYzMDU5ODIyMn0.F-TiepJ8ezlxE4n53gzAf38IMSRgm2S1x5MDPPunkGw"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmlsbCIsImlhdCI6MTYzMDU5ODIyMn0.F-TiepJ8ezlxE4n53gzAf38IMSRgm2S1x5MDPPunkGw"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Jill"
}